config/routes.rb
Rails.application.routes.draw do
  resources :gamifications, except: [:new,:show,:index,:edit,:update]
  resources :affairs, :path => "projetos"
  get '/projetos/:affair_id/members/new' => 'project_members#new'
  get '/projetos/:affair_id/members/delete' => 'project_members#delete'
  get '/teste' => 'project_members#teste'
  resources :project_members, except: [:new,:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  scope "/staff" do
    resources :users, except: [:show]
  end
  get '/users/:id' => 'users#show'
  get 'staff/users/:id/gamification' => 'users#gamification'
  get '/staff' => 'staff#index', as: :staff_root
  root 'user#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gamification.rb
class Gamification < ApplicationRecord
    belongs_to :user
end

app/controllers/gamifications_controller.rb
class GamificationsController < StaffController
  before_action :set_gamification, only: [:show, :edit, :update, :destroy]

  # POST /gamifications
  # POST /gamifications.json
  def create
    # @gamification = current_user.gamifications.new(gamification_params)
    @gamification = Gamification.new(gamification_params)
    respond_to do |format|
      if @gamification.save
        format.html { redirect_to action:"edit",controller:"users",id:@gamification.user_id, notice: 'Gamification was successfully created.' }
      else
        format.json { render json: @gamification.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /gamifications/1
  # DELETE /gamifications/1.json
  def destroy
    @gamification.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path, notice: 'Gamification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gamification
      @gamification = Gamification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gamification_params
      params.require(:gamification).permit(:reason, :positive, :negative,:user_id)
    end
end

app/helpers/gamifications_helper.rb
module GamificationsHelper
end

app/views/gamifications/_form.html.erb
<%= form_with(model: gamification, local: true) do |form| %>
  <% if gamification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gamification.errors.count, "error") %> prohibited this gamification from being saved:</h2>

      <ul>
      <% gamification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :reason %>
    <%= form.text_field :reason %>
  </div>

  <div class="field">
    <%= form.label :positive %>
    <%= form.number_field :positive %>
  </div>

  <div class="field">
    <%= form.label :negative %>
    <%= form.number_field :negative %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gamifications/edit.html.erb
<h1>Editing Gamification</h1>

<%= render 'form', gamification: @gamification %>

<%= link_to 'Show', @gamification %> |
<%= link_to 'Back', gamifications_path %>

app/views/gamifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gamifications</h1>

<table>
  <thead>
    <tr>
      <th>Reason</th>
      <th>Positive</th>
      <th>Negative</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gamifications.each do |gamification| %>
      <tr>
        <td><%= gamification.reason %></td>
        <td><%= gamification.positive %></td>
        <td><%= gamification.negative %></td>
        <td><%= link_to 'Show', gamification %></td>
        <td><%= link_to 'Edit', edit_gamification_path(gamification) %></td>
        <td><%= link_to 'Destroy', gamification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gamification', new_gamification_path %>

app/views/gamifications/new.html.erb
<h1>New Gamification</h1>

<%= render 'form', gamification: @gamification %>

<%= link_to 'Back', gamifications_path %>

app/views/gamifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reason:</strong>
  <%= @gamification.reason %>
</p>

<p>
  <strong>Positive:</strong>
  <%= @gamification.positive %>
</p>

<p>
  <strong>Negative:</strong>
  <%= @gamification.negative %>
</p>

<%= link_to 'Edit', edit_gamification_path(@gamification) %> |
<%= link_to 'Back', gamifications_path %>