config/routes.rb
Rails.application.routes.draw do
  resources :gamifications, except: [:new,:show,:index,:edit,:update]
  resources :affairs, :path => "projetos"
  get '/projetos/:affair_id/members/new' => 'project_members#new'
  get '/projetos/:affair_id/members/delete' => 'project_members#delete'
  get '/teste' => 'project_members#teste'
  resources :project_members, except: [:new,:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  scope "/staff" do
    resources :users, except: [:show]
  end
  get '/users/:id' => 'users#show'
  get 'staff/users/:id/gamification' => 'users#gamification'
  get '/staff' => 'staff#index', as: :staff_root
  root 'user#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/affair.rb
class Affair < ApplicationRecord
  has_and_belongs_to_many :users
end

app/controllers/affairs_controller.rb
class AffairsController < StaffController
  before_action :set_affair, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, except: [:show]
  layout "admin_lte_2"
  # GET /affairs
  # GET /affairs.json
  def index
    @affairs = Affair.all
  end

  # GET /affairs/1
  # GET /affairs/1.json
  def show
  end

  # GET /affairs/new
  def new
    @affair = Affair.new
    @users = User.all
  end

  # GET /affairs/1/edit
  def edit
    @users = User.all
  end

  # POST /affairs
  # POST /affairs.json
  def create
    @affair = Affair.new(affair_params)

    respond_to do |format|
      if @affair.save
        format.html { redirect_to @affair, notice: 'Affair was successfully created.' }
        format.json { render :show, status: :created, location: @affair }
      else
        format.html { render :new }
        format.json { render json: @affair.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /affairs/1
  # PATCH/PUT /affairs/1.json
  def update
    if add?
      user = User.find(params[:affair][:users])
      @affair.users << user
      teste = true
      user.histories.each do |h|
        if h.project_name == @affair.name
          teste = false
        end
      end
      if teste
        history = History.new
        history.project_name = @affair.name
        user.histories << history
      end
      redirect_back fallback_location: root_path, notice: 'User was successfully allocated.'
    else
      respond_to do |format|
        if @affair.update(affair_params)
          format.html { redirect_to @affair, notice: 'Affair was successfully updated.' }
          format.json { render :show, status: :ok, location: @affair }
        else
          format.html { render :edit }
          format.json { render json: @affair.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  def members
    set_affaire
    @users = User.all
  end

  # DELETE /affairs/1
  # DELETE /affairs/1.json
  def destroy
    if del?
      @affair.users.delete(User.find(params[:affair][:users]))
      redirect_back(fallback_location: root_path)
    else
      @affair.destroy
      respond_to do |format|
        format.html { redirect_to affairs_url, notice: 'Affair was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_affair
      @affair = Affair.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def affair_params
      params.require(:affair).permit(:name, :users)
    end
    def del?
      params[:commit] == 'Desalocar Membro'
    end
    def add?
      params[:commit] == 'Alocar Membro'
    end
end

app/helpers/affairs_helper.rb
module AffairsHelper
end

app/views/affairs/_form.html.erb
<%= form_with(model: affair, local: true) do |form| %>
  <% if affair.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(affair.errors.count, "error") %> prohibited this affair from being saved:</h2>

      <ul>
      <% affair.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label 'Nome' %><br>
    <%= form.text_field :name %>
  </div>
  <div class="actions">
    <%= form.submit 'Enviar' %>
  </div>
<% end %>

app/views/affairs/edit.html.erb
<%= link_to '', affairs_path,class:"fa fa-chevron-left",style:"font-size:20px;"%>
<div class="projeto-body">
    <h1>Editando Projeto</h1>
</div>
<div class="projeto-body under">
    <%= render 'form', affair: @affair %>
</div>

app/views/affairs/index.html.erb
<div class="projeto-body">
  <h1>Projetos <i class="fa fa-cubes"></i></h1>
</div>
<% @affairs.each do |affair| %>
<div class="projeto-body  under" style="text-align:center;">
    <%= link_to '', affair, method: :delete, data: { confirm: 'Tem Certeza?' },class:"fa fa-times",style:"color:red;float:right;font-size:20px;margin-left:15px;" %>
    <%= link_to '', edit_affair_path(affair), class:"fa fa-pencil",style:"color:#A1CAC6;float:right;font-size:20px;"%>
  <strong style="font-size:20px; "><a href="/projetos/<%=affair.id%>"><i class="fa fa-cube"></i><%=affair.name%></a></strong>
</div>  
<div class="projeto-body under nested"style="background-color:#EFEFEF;">
  <strong style="font-size:15px; ">Membros Alocados <i class="fa fa-users"></i></strong>
<%= link_to  "", "projetos/#{affair.id}/members/delete",class:"fa fa-user-times" ,style:"color:red;float:right;font-size:15px;margin-left:15px;" %>
  <%= link_to  "", "projetos/#{affair.id}/members/new",class:"fa fa-user-plus" ,style:"color:green;float:right;font-size:15px;" %>
</div>
  <% if affair.users != nil %>
    <%affair.users.each do |user|%>
    <div class="projeto-body under nested">
      <i class="fa fa-user"></i> <%= user.name %>
    </div>
    <%end%>
  <%end%>
<%end%>
<div class="novo"><%= link_to '', new_affair_path, class:"fa fa-plus-circle", style:"color:green;"%></div>

app/views/affairs/new.html.erb
<h1>Novo Projeto</h1>

<%= render 'form', affair: @affair %>

<%= link_to 'Back', affairs_path %>

app/views/affairs/show.html.erb
<%= link_to '', affairs_path,class:"fa fa-chevron-left",style:"font-size:20px;" %>
<div class="projeto-body">
    <%if current_user.try(:admin?)%>
        <%= link_to '', edit_affair_path(@affair), class:"fa fa-pencil",style:"color:#222D32;float:right;font-size:20px;"%>
    <%end%>
    <h1><%=@affair.name%></h1>
</div>
<div class="projeto-body under"style="background-color:#EFEFEF;">
    <strong style="font-size:15px; ">Membros Alocados <i class="fa fa-users"></i></strong>
</div>
<% @affair.users.each do |user| %>
<div class="profile-body under nested" style="background-color:rgba(159, 201, 197,0.3);">
    <%unless user.avatar.file.nil?%>
        <%= image_tag  user.avatar_url,size:"90x90", class:"img-circle" %>
    <%else%>
        <%= image_tag  "default",size:"90x90",class:"img-circle" %>
    <%end%>
    <div class="profile-card">
        <h3><a href="/users/<%=user.id%>"><%= user.name %></a><br>
        <small><%= user.role %></small></h1>
        <p class="indent"><i class="fa fa-envelope"></i> <%= user.email %></p>
    </div>
</div>
<%end%>